### ISSUE TITLE
set day standard to dd/mm/yy in weather report

### ISSUE THREAD

**Issue by plooj** [mossizprypjat/mossizprypjat.nekoweb#17]
![image](https://github.com/user-attachments/assets/b7f63aa7-cf01-4240-a6b6-535cda495f0d)

**LOOK AT HOW UGLY THIS IS I CANT READ THIS I WILL KILL MYSELF IF I SEE THIS ONEMORE TIME. I EXPECT BETTER THAN THIS UYOU KNWO I USE THIS AS THE MY ONLY THING TO SEE THE WEATHER I AMOST DIED BEACUASE I WAS IN A STORM BEACAUSE I READ THE DATE WRONG. YOU WILL  KILL PEOPLE THIS WAY FIX IT!!!!!!!!!!!
NNNNNOOOOOWWWWWWW**

:3

**Comment by mossizprypjat** [comment]
i fixed it :3

**Comment by plooj** [comment]
Yippieeee
